(async function(){
  const $=id=>document.getElementById(id);
  const els={menu:$('menu'),shade:$('shade'),title:$('title'),dateLine:$('dateLine'),productSearch:$('productSearch'),clearSearch:$('clearSearch'),dropdown:$('dropdown'),warning:$('warning'),pallets:$('pallets'),boxesPerPallet:$('boxesPerPallet'),unitsPerBox:$('unitsPerBox'),unit:$('unit'),liveResult:$('liveResult'),liveCalc:$('liveCalc'),addItem:$('addItem'),currentItems:$('currentItems'),itemCount:$('itemCount'),finishDoc:$('finishDoc'),productsList:$('productsList'),toggleBulk:$('toggleBulk'),bulkBox:$('bulkBox'),bulkNames:$('bulkNames'),bulkAdd:$('bulkAdd'),previewPaper:$('previewPaper'),showCalc:$('showCalc'),editDoc:$('editDoc'),createPdf:$('createPdf'),historyList:$('historyList'),exportBackup:$('exportBackup'),importBackup:$('importBackup'),clearCurrent:$('clearCurrent')};
  let products=[], current={id:'current',items:[],date:'',time:''}, settings={id:'settings',showCalc:true}, selected=null, previewDoc=null, previewFromHistory=false;
  const today=()=>new Date().toLocaleDateString('uk-UA');
  const now=()=>new Date().toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'});
  const prettyDate=()=>new Date().toLocaleDateString('uk-UA',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})+' · '+now();
  const num=v=>Number(String(v).replace(',','.'))||0;
  const configured=p=>p&&num(p.boxesPerPallet)>0&&num(p.unitsPerBox)>0&&p.unit;
  const toast=msg=>{const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)};
  const saveCurrent=()=>AppDB.put('current', current);
  const saveSettings=()=>AppDB.put('settings', settings);
  function setDateLine(){els.dateLine.textContent=prettyDate()} setInterval(setDateLine,30000);
  function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view).classList.add('active');els.title.textContent=({home:'Облік продукції',products:'Довідник продукції',history:'Історія документів',settings:'Налаштування',about:'Про програму',preview:'Попередній перегляд документа'})[view]||'Облік';closeMenu(); if(view==='products')renderProducts(); if(view==='history')renderHistory(); if(view==='home')setTimeout(()=>els.productSearch.focus(),80);}
  function openMenu(){els.menu.classList.add('open');els.shade.classList.add('open')} function closeMenu(){els.menu.classList.remove('open');els.shade.classList.remove('open')}
  $('openMenu').onclick=openMenu;$('closeMenu').onclick=closeMenu;els.shade.onclick=closeMenu;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));

  await AppDB.open();
  products=(await AppDB.all('products')).sort((a,b)=>a.name.localeCompare(b.name,'uk'));
  current=await AppDB.get('current','current')||current;
  settings=await AppDB.get('settings','settings')||settings;
  setDateLine();
  els.showCalc.checked=!!settings.showCalc;
  renderCurrent(); renderDropdown(''); calcLive();

  function renderDropdown(query){const q=query.trim().toLowerCase();const list=products.filter(p=>p.name.toLowerCase().includes(q)); if(!els.dropdown.classList.contains('open')) return; els.dropdown.innerHTML=list.length?list.map(p=>`<div class="drop-item" data-id="${p.id}"><b>${escapeHtml(p.name)}</b><small>${configured(p)?'налаштовано':'не налаштовано'}</small></div>`).join(''):'<div class="drop-item"><small>Нічого не знайдено</small></div>'; els.dropdown.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>selectProduct(x.dataset.id));}
  function selectProduct(id){selected=products.find(p=>p.id===id)||null;if(!selected)return;els.productSearch.value=selected.name;els.dropdown.classList.remove('open');els.boxesPerPallet.value=selected.boxesPerPallet||'';els.unitsPerBox.value=selected.unitsPerBox||'';els.unit.value=selected.unit||'пачки';showWarning();calcLive();setTimeout(()=>els.pallets.focus(),50)}
  function showWarning(){if(selected&&!configured({...selected,boxesPerPallet:els.boxesPerPallet.value,unitsPerBox:els.unitsPerBox.value,unit:els.unit.value})){els.warning.classList.remove('hidden');els.warning.innerHTML=`Продукція не налаштована. Заповніть ящики, одиниці в ящику та одиницю обліку в довіднику. <button class="mini" id="goEditSelected">Редагувати</button>`;$('goEditSelected').onclick=()=>openEdit(selected.id)}else els.warning.classList.add('hidden')}
  function calcLive(){const p=num(els.pallets.value), b=num(els.boxesPerPallet.value), u=num(els.unitsPerBox.value), unit=els.unit.value||'пачки'; const boxes=p*b,total=boxes*u; els.liveResult.textContent=`${PDFGen.fmt(total)} ${unit}`; els.liveCalc.textContent=p&&b&&u?`${PDFGen.fmt(p)}×${PDFGen.fmt(b)}×${PDFGen.fmt(u)} = ${PDFGen.fmt(total)} ${unit}`:'Заповніть піддони та параметри'; showWarning();}
  els.productSearch.onfocus=()=>{els.dropdown.classList.add('open');renderDropdown(els.productSearch.value)}; els.productSearch.oninput=()=>{selected=null;els.dropdown.classList.add('open');renderDropdown(els.productSearch.value);showWarning();}; els.clearSearch.onclick=()=>{els.productSearch.value='';selected=null;els.dropdown.classList.add('open');renderDropdown('');els.productSearch.focus();}; [els.pallets,els.boxesPerPallet,els.unitsPerBox,els.unit].forEach(e=>e.addEventListener('input',calcLive));
  document.addEventListener('click',e=>{if(!e.target.closest('.form-card'))els.dropdown.classList.remove('open')});

  els.addItem.onclick=async()=>{if(!selected){toast('Спочатку вибери продукцію');return} const pallets=num(els.pallets.value), b=num(els.boxesPerPallet.value), u=num(els.unitsPerBox.value), unit=els.unit.value; if(pallets<=0){toast('Введи кількість піддонів');els.pallets.focus();return} if(b<=0||u<=0){toast('Продукція не налаштована');return} const boxes=pallets*b,total=boxes*u,calc=`${PDFGen.fmt(pallets)}×${PDFGen.fmt(b)}×${PDFGen.fmt(u)}`; const existing=current.items.find(i=>i.productId===selected.id||i.name===selected.name); if(existing){existing.pallets+=pallets;existing.boxes+=boxes;existing.total+=total;existing.calc=`${PDFGen.fmt(existing.pallets)}×${PDFGen.fmt(b)}×${PDFGen.fmt(u)}`;existing.boxesPerPallet=b;existing.unitsPerBox=u;existing.unit=unit;}else current.items.push({id:AppDB.uid(),productId:selected.id,name:selected.name,pallets,boxes,total,calc,boxesPerPallet:b,unitsPerBox:u,unit}); current.date=today(); current.time=now(); await saveCurrent(); renderCurrent(); els.pallets.value=''; calcLive(); els.pallets.focus(); };
  function renderCurrent(){const items=current.items||[];els.itemCount.textContent=`${items.length} позицій`; if(!items.length){els.currentItems.className='list empty';els.currentItems.textContent='Позицій ще немає';return} els.currentItems.className='list'; els.currentItems.innerHTML=items.map(i=>itemHTML(i,true)).join(''); els.currentItems.querySelectorAll('[data-del-item]').forEach(b=>b.onclick=async()=>{current.items=current.items.filter(i=>i.id!==b.dataset.delItem);await saveCurrent();renderCurrent();}); els.currentItems.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>editDocItem(b.dataset.editItem));}
  function itemHTML(i,actions){return `<div class="item"><h3>${escapeHtml(i.name)}</h3><div class="item-grid"><div><span>Піддони</span><b>${PDFGen.fmt(i.pallets)}</b></div><div><span>Ящики</span><b>${PDFGen.fmt(i.boxes)}</b></div><div><span>Розрахунок</span><b>${escapeHtml(i.calc)}</b></div><div><span>Разом</span><b>${PDFGen.fmt(i.total)} ${escapeHtml(i.unit)}</b></div></div>${actions?`<div class="item-actions"><button class="mini" data-edit-item="${i.id}">Редагувати</button><button class="mini danger" data-del-item="${i.id}">Видалити</button></div>`:''}</div>`}
  function editDocItem(id){const i=current.items.find(x=>x.id===id); if(!i)return; selected=products.find(p=>p.id===i.productId)||{id:i.productId,name:i.name}; els.productSearch.value=i.name; els.boxesPerPallet.value=i.boxesPerPallet; els.unitsPerBox.value=i.unitsPerBox; els.unit.value=i.unit; els.pallets.value=i.pallets; current.items=current.items.filter(x=>x.id!==id); saveCurrent().then(renderCurrent); calcLive(); els.pallets.focus();}
  els.finishDoc.onclick=()=>{if(!(current.items||[]).length){toast('Документ порожній');return} previewDoc=AppDB.clone({...current,date:current.date||today(),time:current.time||now()}); previewFromHistory=false; renderPreview(); setView('preview')};
  els.editDoc.onclick=()=>setView('home'); els.showCalc.onchange=async()=>{settings.showCalc=els.showCalc.checked;await saveSettings();renderPreview()};
  function renderPreview(){els.showCalc.checked=!!settings.showCalc; els.previewPaper.innerHTML=PDFGen.buildDocumentHTML(previewDoc||current,settings.showCalc);}
  els.createPdf.onclick=async()=>{const doc=AppDB.clone(previewDoc||current); doc.date=doc.date||today(); doc.time=doc.time||now(); if(!previewFromHistory){const saved={id:AppDB.uid(),date:doc.date,time:doc.time,items:AppDB.clone(doc.items),showCalc:settings.showCalc,totals:PDFGen.totals(doc.items)}; await AppDB.put('documents',saved); current={id:'current',items:[],date:'',time:''}; await saveCurrent(); renderCurrent(); previewFromHistory=true; previewDoc=saved;} await PDFGen.savePdf(doc,settings.showCalc); toast('PDF створено і збережено в історії');};

  els.toggleBulk.onclick=()=>els.bulkBox.classList.toggle('hidden');
  els.bulkAdd.onclick=async()=>{const names=els.bulkNames.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);let added=0,skipped=0;for(const name of names){if(products.some(p=>p.name.toLowerCase()===name.toLowerCase())){skipped++;continue} const p={id:AppDB.uid(),name,boxesPerPallet:'',unitsPerBox:'',unit:'пачки',createdAt:new Date().toISOString()};products.push(p);await AppDB.put('products',p);added++;}products.sort((a,b)=>a.name.localeCompare(b.name,'uk'));els.bulkNames.value='';renderProducts();renderDropdown('');toast(`Додано: ${added}. Пропущено: ${skipped}`);};
  function renderProducts(){if(!products.length){els.productsList.className='list empty';els.productsList.textContent='Довідник порожній';return} els.productsList.className='list';els.productsList.innerHTML=products.map(p=>`<div class="item"><h3>${escapeHtml(p.name)}</h3><span class="badge ${configured(p)?'ok':'bad'}">${configured(p)?'налаштовано':'не налаштовано'}</span><div class="item-grid" style="margin-top:10px"><div><span>Ящ./підд.</span><b>${p.boxesPerPallet||'—'}</b></div><div><span>Од./ящ.</span><b>${p.unitsPerBox||'—'}</b></div><div><span>Одиниця</span><b>${p.unit||'—'}</b></div></div><div class="item-actions"><button class="mini" data-edit-product="${p.id}">Редагувати</button><button class="mini danger" data-del-product="${p.id}">Видалити</button></div></div>`).join('');els.productsList.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openEdit(b.dataset.editProduct));els.productsList.querySelectorAll('[data-del-product]').forEach(b=>b.onclick=async()=>{if(confirm('Видалити продукцію?')){products=products.filter(p=>p.id!==b.dataset.delProduct);await AppDB.del('products',b.dataset.delProduct);renderProducts();}})}
  function openEdit(id){const p=products.find(x=>x.id===id);if(!p)return;const frag=$('editProductTemplate').content.cloneNode(true);document.body.appendChild(frag);const wrap=document.querySelector('.modal-wrap');$('editName').value=p.name;$('editBoxes').value=p.boxesPerPallet||'';$('editUnits').value=p.unitsPerBox||'';$('editUnit').value=p.unit||'пачки';$('cancelEdit').onclick=()=>wrap.remove();$('saveEdit').onclick=async()=>{const name=$('editName').value.trim();if(!name){toast('Назва порожня');return} if(products.some(x=>x.id!==p.id&&x.name.toLowerCase()===name.toLowerCase())){toast('Така назва вже є');return}p.name=name;p.boxesPerPallet=num($('editBoxes').value)||'';p.unitsPerBox=num($('editUnits').value)||'';p.unit=$('editUnit').value;await AppDB.put('products',p);products.sort((a,b)=>a.name.localeCompare(b.name,'uk'));wrap.remove();renderProducts();renderDropdown(''); if(selected&&selected.id===p.id)selectProduct(p.id);toast('Збережено');};}

  async function renderHistory(){const docs=(await AppDB.all('documents')).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)); if(!docs.length){els.historyList.className='list empty';els.historyList.textContent='Історія порожня';return} els.historyList.className='list'; els.historyList.innerHTML=docs.map(d=>`<div class="item"><h3>Документ від ${escapeHtml(d.date)} · ${escapeHtml(d.time)}</h3><p class="muted">${(d.items||[]).length} позицій</p><div class="item-actions"><button class="mini" data-view-doc="${d.id}">Переглянути</button><button class="mini" data-pdf-doc="${d.id}">PDF</button><button class="mini danger" data-del-doc="${d.id}">Видалити</button></div></div>`).join('');els.historyList.querySelectorAll('[data-view-doc]').forEach(b=>b.onclick=async()=>{previewDoc=await AppDB.get('documents',b.dataset.viewDoc);previewFromHistory=true;settings.showCalc=previewDoc.showCalc!==undefined?previewDoc.showCalc:settings.showCalc;await saveSettings();renderPreview();setView('preview')});els.historyList.querySelectorAll('[data-pdf-doc]').forEach(b=>b.onclick=async()=>{const d=await AppDB.get('documents',b.dataset.pdfDoc);await PDFGen.savePdf(d,d.showCalc!==undefined?d.showCalc:settings.showCalc)});els.historyList.querySelectorAll('[data-del-doc]').forEach(b=>b.onclick=async()=>{if(confirm('Видалити документ з історії?')){await AppDB.del('documents',b.dataset.delDoc);renderHistory();}})}

  els.exportBackup.onclick=async()=>{const backup={version:1,createdAt:new Date().toISOString(),products:await AppDB.all('products'),documents:await AppDB.all('documents'),current:await AppDB.all('current'),settings:await AppDB.all('settings')}; const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`backup_${today().replaceAll('.','-')}_${now().replace(':','-')}.json`; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  els.importBackup.onchange=async()=>{const file=els.importBackup.files[0]; if(!file)return; try{const data=JSON.parse(await file.text()); if(!confirm('Імпорт замінить поточні дані. Продовжити?'))return; await AppDB.replaceStore('products',data.products||[]); await AppDB.replaceStore('documents',data.documents||[]); await AppDB.replaceStore('current',data.current||[{id:'current',items:[]}]); await AppDB.replaceStore('settings',data.settings||[{id:'settings',showCalc:true}]); products=(await AppDB.all('products')).sort((a,b)=>a.name.localeCompare(b.name,'uk')); current=await AppDB.get('current','current')||{id:'current',items:[]}; settings=await AppDB.get('settings','settings')||{id:'settings',showCalc:true}; renderCurrent();renderProducts();toast('Резервну копію відновлено');setView('home');}catch(e){toast('Не вдалося імпортувати файл')} finally{els.importBackup.value='';}};
  els.clearCurrent.onclick=async()=>{if(confirm('Очистити поточний документ?')){current={id:'current',items:[],date:'',time:''};await saveCurrent();renderCurrent();toast('Очищено')}};
  function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
  if('serviceWorker' in navigator){navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
})();
