import{openDB}from'./db.js';
import{loadProducts,products,searchProducts,isConfigured,addManyProducts,saveProduct,removeProduct,findProduct}from'./products.js';
import{loadCurrent,currentDoc,addToCurrent,removeCurrentItem,clearCurrent,calcLine,fmt,n}from'./document.js';
import{loadHistory,history,saveDocument,deleteDocument}from'./history.js';
import{loadSettings,saveSettings,settings}from'./settings.js';
import{renderPreview}from'./preview.js';
import{createPDF}from'./pdf.js';
import{$,$$,toast,esc}from'./ui.js';

let selectedProduct=null;
let currentRoute='home';
let previewContext={type:'current',doc:null};

const els={
 pageTitle:$('#pageTitle'),today:$('#todayLabel'),menu:$('#sideMenu'),overlay:$('#overlay'),
 search:$('#productSearch'),clearSearch:$('#clearSearchBtn'),dropdown:$('#productDropdown'),pallets:$('#palletsInput'),boxes:$('#boxesPerPalletInput'),units:$('#unitsPerBoxInput'),unit:$('#unitInput'),warning:$('#setupWarning'),liveResult:$('#liveResult'),liveCalc:$('#liveCalc'),add:$('#addItemBtn'),items:$('#currentItems'),count:$('#currentCount'),finish:$('#finishDocBtn'),
 bulkBox:$('#bulkAddBox'),bulkNames:$('#bulkNamesInput'),productsList:$('#productsList'),dialog:$('#productDialog'),form:$('#productForm'),editId:$('#editProductId'),editName:$('#editName'),editBoxes:$('#editBoxes'),editUnits:$('#editUnits'),editUnit:$('#editUnit'),
 preview:$('#pdfPreview'),showCalc:$('#showCalcToggle'),settingsShowCalc:$('#settingsShowCalc'),historyList:$('#historyList')
};

window.addEventListener('DOMContentLoaded',init);
async function init(){await openDB();await Promise.all([loadSettings(),loadProducts(),loadCurrent(),loadHistory()]);bind();dateTick();setInterval(dateTick,30000);els.showCalc.checked=settings.showCalc;els.settingsShowCalc.checked=settings.showCalc;renderAll();route('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
function bind(){
 $('#openMenuBtn').onclick=openMenu;$('#closeMenuBtn').onclick=closeMenu;els.overlay.onclick=closeMenu;
 $$('.menu-list button').forEach(b=>b.onclick=()=>{route(b.dataset.route);closeMenu()});
 els.search.addEventListener('focus',()=>renderDropdown(true));els.search.addEventListener('input',()=>{selectedProduct=null;renderDropdown(true);updateLive()});els.clearSearch.onclick=()=>{els.search.value='';selectedProduct=null;renderDropdown(true);updateLive();els.search.focus()};
 document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))els.dropdown.classList.remove('open')});
 [els.pallets,els.boxes,els.units,els.unit].forEach(x=>x.addEventListener('input',updateLive));
 els.add.onclick=addCurrentItem;
 els.finish.onclick=()=>{if(!currentDoc.items.length)return toast('Спочатку додай хоч одну позицію');previewContext={type:'current',doc:null};renderPreview(els.preview,currentDoc.items,settings.showCalc);route('preview')};
 $('#editDocBtn').onclick=()=>route(previewContext.type==='history'?'history':'home');
 els.showCalc.onchange=async()=>{await saveSettings({showCalc:els.showCalc.checked});els.settingsShowCalc.checked=settings.showCalc;renderPreview(els.preview,currentDoc.items,settings.showCalc)};
 els.settingsShowCalc.onchange=async()=>{await saveSettings({showCalc:els.settingsShowCalc.checked});els.showCalc.checked=settings.showCalc};
 $('#createPdfBtn').onclick=async()=>{if(previewContext.type==='history'&&previewContext.doc){createPDF(previewContext.doc.items,previewContext.doc.showCalc,previewContext.doc);return}if(!currentDoc.items.length)return toast('Документ порожній');const doc=await saveDocument(currentDoc.items,settings.showCalc);createPDF(doc.items,doc.showCalc,doc);await clearCurrent();await loadHistory();renderAll();route('history');toast('PDF створено і документ збережено')};
 $('#showBulkAddBtn').onclick=()=>{els.bulkBox.classList.toggle('hidden');els.bulkNames.focus()};
 $('#bulkAddBtn').onclick=bulkAdd;
 $('#saveProductBtn').onclick=saveProductFromDialog;
 $('#clearCurrentBtn').onclick=async()=>{if(confirm('Очистити поточний документ?')){await clearCurrent();renderCurrent();toast('Поточний документ очищено')}};
}
function route(name){currentRoute=name;$$('.view').forEach(v=>v.classList.remove('active'));const id=name==='home'?'view-home':`view-${name}`;$('#'+id)?.classList.add('active');const titles={home:'Облік продукції',products:'Довідник продукції',history:'Історія документів',settings:'Налаштування',about:'Про програму',preview:'Попередній перегляд документа'};els.pageTitle.textContent=titles[name]||'Облік продукції';if(name==='preview')renderPreview(els.preview,currentDoc.items,settings.showCalc);if(name==='products')renderProducts();if(name==='history')renderHistory();}
function openMenu(){els.menu.classList.add('open');els.overlay.classList.add('show');els.menu.setAttribute('aria-hidden','false')}
function closeMenu(){els.menu.classList.remove('open');els.overlay.classList.remove('show');els.menu.setAttribute('aria-hidden','true')}
function dateTick(){const d=new Date();els.today.textContent=d.toLocaleDateString('uk-UA',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})+' · '+d.toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'})}
function renderAll(){renderCurrent();renderProducts();renderHistory();renderDropdown(false);updateLive()}
function renderDropdown(open=false){const list=searchProducts(els.search.value);els.dropdown.innerHTML=list.length?list.map(p=>`<button data-id="${p.id}"><b>${esc(p.name)}</b><small>${isConfigured(p)?`${fmt(p.boxesPerPallet)} ящ./підд. · ${fmt(p.unitsPerBox)} ${p.unit}/ящ.`:'не налаштовано'}</small></button>`).join(''):'<button disabled>Нічого не знайдено</button>';els.dropdown.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>selectProduct(b.dataset.id));els.dropdown.classList.toggle('open',open)}
function selectProduct(id){selectedProduct=findProduct(id);if(!selectedProduct)return;els.search.value=selectedProduct.name;els.boxes.value=selectedProduct.boxesPerPallet||'';els.units.value=selectedProduct.unitsPerBox||'';els.unit.value=selectedProduct.unit||'пачки';els.dropdown.classList.remove('open');showSetupWarning();updateLive();setTimeout(()=>els.pallets.focus(),40)}
function showSetupWarning(){if(!selectedProduct||isConfigured(selectedProduct)){els.warning.classList.add('hidden');els.add.disabled=false;return}els.warning.innerHTML=`Продукція «${esc(selectedProduct.name)}» не налаштована. Заповни ящики, одиниці та одиницю обліку. <br><button id="goEditSelected">Редагувати</button>`;els.warning.classList.remove('hidden');els.add.disabled=true;$('#goEditSelected').onclick=()=>openProductEdit(selectedProduct.id)}
function updateLive(){const line=calcLine(els.pallets.value,els.boxes.value,els.units.value,els.unit.value);const valid=line.pallets>0&&line.boxesPerPallet>0&&line.unitsPerBox>0;els.liveResult.textContent=valid?`${fmt(line.total)} ${line.unit}`:'0';els.liveCalc.textContent=valid?`${fmt(line.pallets)} × ${fmt(line.boxesPerPallet)} × ${fmt(line.unitsPerBox)} = ${fmt(line.total)} ${line.unit}`:'Оберіть продукцію і введіть піддони'}
async function addCurrentItem(){if(!selectedProduct)return toast('Спочатку вибери продукцію');if(!isConfigured({...selectedProduct,boxesPerPallet:els.boxes.value,unitsPerBox:els.units.value,unit:els.unit.value}))return toast('Заповни параметри продукції. Нуль тут не пройде 🙂');const line=calcLine(els.pallets.value,els.boxes.value,els.units.value,els.unit.value);if(line.pallets<=0)return toast('Введи кількість піддонів');await addToCurrent(selectedProduct,line);els.pallets.value='';updateLive();renderCurrent();setTimeout(()=>els.pallets.focus(),40)}
function renderCurrent(){els.count.textContent=`${currentDoc.items.length} позицій`;if(!currentDoc.items.length){els.items.className='items-list empty-state';els.items.textContent='Позицій ще немає';return}els.items.className='items-list';els.items.innerHTML=currentDoc.items.map(i=>`<article class="item-card"><div class="item-top"><div class="item-title">${esc(i.productName)}</div><button class="small-btn danger" data-del-current="${i.id}">Видалити</button></div><div class="item-grid"><div class="metric"><span>Піддони</span><b>${fmt(i.pallets)}</b></div><div class="metric"><span>Ящики</span><b>${fmt(i.boxes)}</b></div><div class="metric"><span>Розрахунок</span><b>${esc(i.calc)}</b></div><div class="metric"><span>Разом</span><b>${fmt(i.total)} ${esc(i.unit)}</b></div></div></article>`).join('');els.items.querySelectorAll('[data-del-current]').forEach(b=>b.onclick=async()=>{await removeCurrentItem(b.dataset.delCurrent);renderCurrent()})}
async function bulkAdd(){const res=await addManyProducts(els.bulkNames.value);els.bulkNames.value='';renderProducts();renderDropdown(false);toast(`Додано: ${res.added}. Пропущено: ${res.skipped}`)}
function renderProducts(){if(!products.length){els.productsList.className='items-list empty-state';els.productsList.textContent='Довідник порожній';return}els.productsList.className='items-list';els.productsList.innerHTML=products.map(p=>`<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(p.name)}</div><span class="badge ${isConfigured(p)?'ok':'warn'}">${isConfigured(p)?'налаштовано':'не налаштовано'}</span></div></div><div class="item-grid"><div class="metric"><span>Ящ./підд.</span><b>${fmt(p.boxesPerPallet||0)}</b></div><div class="metric"><span>Од./ящ.</span><b>${fmt(p.unitsPerBox||0)}</b></div><div class="metric"><span>Одиниця</span><b>${esc(p.unit||'пачки')}</b></div></div><div class="item-actions"><button class="small-btn" data-edit-product="${p.id}">Редагувати</button><button class="small-btn danger" data-delete-product="${p.id}">Видалити</button></div></article>`).join('');els.productsList.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProductEdit(b.dataset.editProduct));els.productsList.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=async()=>{if(confirm('Видалити продукцію?')){await removeProduct(b.dataset.deleteProduct);renderProducts();renderDropdown(false)}})}
function openProductEdit(id){const p=findProduct(id);if(!p)return;els.editId.value=p.id;els.editName.value=p.name;els.editBoxes.value=p.boxesPerPallet||'';els.editUnits.value=p.unitsPerBox||'';els.editUnit.value=p.unit||'пачки';els.dialog.showModal();}
async function saveProductFromDialog(e){e.preventDefault();const p={id:els.editId.value,name:els.editName.value,boxesPerPallet:els.editBoxes.value,unitsPerBox:els.editUnits.value,unit:els.editUnit.value};if(!p.name.trim())return toast('Назва порожня');await saveProduct(p);els.dialog.close();selectedProduct=findProduct(p.id);if(selectedProduct){els.search.value=selectedProduct.name;els.boxes.value=selectedProduct.boxesPerPallet||'';els.units.value=selectedProduct.unitsPerBox||'';els.unit.value=selectedProduct.unit||'пачки'}showSetupWarning();renderProducts();renderDropdown(false);updateLive();toast('Збережено')}
function renderHistory(){if(!history.length){els.historyList.className='items-list empty-state';els.historyList.textContent='Історія порожня';return}els.historyList.className='items-list';els.historyList.innerHTML=history.map(d=>`<article class="item-card"><div class="item-top"><div><div class="item-title">${esc(d.date)} · ${esc(d.time)}</div><small>${d.items.length} позицій · піддонів: ${fmt(d.totals.pallets)} · ящиків: ${fmt(d.totals.boxes)}</small></div></div><div class="item-actions"><button class="small-btn" data-pdf-doc="${d.id}">PDF</button><button class="small-btn" data-view-doc="${d.id}">Переглянути</button><button class="small-btn danger" data-del-doc="${d.id}">Видалити</button></div></article>`).join('');els.historyList.querySelectorAll('[data-pdf-doc]').forEach(b=>b.onclick=()=>{const d=history.find(x=>x.id===b.dataset.pdfDoc);if(d)createPDF(d.items,d.showCalc,d)});els.historyList.querySelectorAll('[data-view-doc]').forEach(b=>b.onclick=()=>{const d=history.find(x=>x.id===b.dataset.viewDoc);if(d){previewContext={type:'history',doc:d};els.showCalc.checked=d.showCalc;renderPreview(els.preview,d.items,d.showCalc);route('preview')}});els.historyList.querySelectorAll('[data-del-doc]').forEach(b=>b.onclick=async()=>{if(confirm('Видалити документ з історії?')){await deleteDocument(b.dataset.delDoc);renderHistory()}})}
